pipeline {
    agent any

    tools {
        nodejs 'nodejs'   // Configure in Jenkins Global Tools
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Annapragada-Neeraj/onlineapp.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                sh 'npm test || echo "No tests found"'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }
    }
}
